DESCRIBE PESSOAS;

ALTER TABLE PESSOAS
ADD COLUMN PROFISSAO VARCHAR(100);
DESCRIBE PESSOAS;

SELECT * FROM PESSOAS;

UPDATE PESSOAS SET PROFISSAO = 'TECNICO' WHERE ID = '1';
ALTER TABLE PESSOAS
MODIFY PROFISSAO VARCHAR(20) DEFAULT '';

ALTER TABLE PESSOAS
CHANGE PROFISSAO PROF VARCHAR(20);

DESCRIBE PESSOAS;

ALTER TABLE PESSOAS
RENAME TO GAFANHOTOS;


