CREATE DATABASE CADASTRO
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

CREATE TABLE PESSOAS(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
SEXO ENUM('M' , 'F'),
PESO DECIMAL (5,2),
ALTURA DECIMAL (3,2),
NACIONALIDADE VARCHAR (20) DEFAULT 'BRASIL',
NASCIMENTO DATE,
PRIMARY KEY (ID)
) DEFAULT CHARSET = UTF8;
INSERT INTO PESSOAS
(ID, NOME, NASCIMENTO, SEXO, PESO, ALTURA, NACIONALIDADE)
VALUES
(DEFAULT,'LUIS', '1984-05-07', 'M', '69', '1.70','IRLANDA');

SELECT * FROM PESSOAS;