USE CADASTRO;
CREATE TABLE IF NOT EXISTS  CURSOS(
NOME VARCHAR(30) NOT NULL UNIQUE,
DESCRICAO TEXT,
CARGA INT UNSIGNED,
TOTAULAS INT unsigned,
ANO YEAR DEFAULT '2016'
) DEFAULT CHARSET = UTF8;

DESCRIBE CURSOS;

ALTER TABLE CURSOS ADD COLUMN IDCURSO INT FIRST;
DESCRIBE CURSOS;

ALTER TABLE CURSOS
ADD PRIMARY KEY (IDCURSO);
DESCRIBE CURSOS;

